### ISSUE TITLE
basic filtering for application logs in a job dashboard

### ISSUE THREAD

**Issue by atinsood** [project-codeflare/codeflare-cli#179]
## Objective

Currently all logs show under the application logs and there is no way to filter the logs. As a user, at times I might be interested in some easy filters:
1. I want to see logs belonging to a specific worker/node/process only. 
2. I want to see logs matching a certain regex

**Comment by starpit** [comment]
UI: PatternFly Select with favorites and typeahead

**Comment by starpit** [comment]
Searching is possible. In order to do filtering, we would need to write an xterm.js addon. There is already an `xterm-addon-search`, but no `xterm-addon-filter`. See: https://github.com/xtermjs/xterm.js/tree/master/addons
