### ISSUE TITLE
Could --help and version be added?

### ISSUE THREAD

**Issue by nheidloff** [project-codeflare/codeflare-cli#791]
It would be great to add the two standard parameters to get help about the currently installed CLI

**Comment by starpit** [comment]
thanks for the feedback! currently there is `codeflare version` (no dashes). i agree that the standard `-v/--version` would be nice.

**Comment by starpit** [comment]
this should be improved in `codeflare` 2.9.1

ref: https://github.com/guidebooks/madwizard/pull/655 https://github.com/guidebooks/madwizard/pull/656
ref: https://github.com/kubernetes-sigs/kui/pull/9311 https://github.com/kubernetes-sigs/kui/pull/9312 https://github.com/kubernetes-sigs/kui/pull/9313
