### ISSUE TITLE
Adjust release steps to contain complete and detailed release description

### ISSUE THREAD

**Issue by sutaakar** [project-codeflare/codeflare-cli#994]
Current release steps defined in https://github.com/project-codeflare/codeflare-cli/tree/main/docs/release seems to be incomplete.
I don't see proper description of release template parameters and instructions of getting proper values.

Release steps should be enhanced to allow a person with limited knowledge to figure out how the release should be performed, what are possible external dependencies for this release.

**Comment by ChughShilpa** [comment]
@anishasthana  updated that Nick (the maintainer for the repo) is planning to effectively deprecate the repo altogether --will be moving the cli functionality into the sdk instead

@sutaakar So does this still needs to be done or can we close this issue ?

**Comment by sutaakar** [comment]
I think it can be closed.
